import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@app/components/header/header.components';
import classNames from 'classnames';
import { ReactNode } from 'react';
import { ShopProvider } from '@app/context/shopContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ShopProvider>
      <html lang='en'>
        <body
          className={classNames(
            inter.className,
            'flex flex-col justify-between min-h-screen'
          )}
        >
          <Header />

          <main>{children}</main>

          <footer>Footer</footer>
        </body>
      </html>
    </ShopProvider>
  );
}
